package ch.cevi.db.client.configuration;

import java.util.Locale;
import java.util.ResourceBundle;

public class Texts {

	public final static String MAIN_WINDOW_TITLE = "MAIN_WINDOW_TITLE";

	public final static String ABOUT_DIALOG_TITLE = "ABOUT_DIALOG_TITLE";

	public final static String ABOUT_DIALOG_VERSION_LABEL = "ABOUT_DIALOG_VERSION_LABEL";

	public final static String ABOUT_DIALOG_RELEASE_DATE_LABEL = "ABOUT_DIALOG_RELEASE_DATE_LABEL";
	
	public final static String ABOUT_DIALOG_JVM_NAME_AND_VERSION_LABEL = "ABOUT_DIALOG_JVM_NAME_AND_VERSION_LABEL";

	public final static String ABOUT_DIALOG_LICENSE_LABEL = "ABOUT_DIALOG_LICENSE_LABEL";

	public static final String ABOUT_DIALOG_OK_BUTTON_LABEL = "ABOUT_DIALOG_OK_BUTTON_LABEL";

	public final static String MENU_FILE_MENU_TITLE = "MENU_FILE_MENU_TITLE";

	public final static String MENU_HELP_MENU_TITLE = "MENU_HELP_MENU_TITLE";

	public static final String MENU_FILE_MENU_CONNECT_ITEM = "MENU_FILE_MENU_CONNECT_ITEM";

	public static final String MENU_FILE_MENU_EXIT_ITEM = "MENU_FILE_MENU_EXIT_ITEM";

	public static final String MENU_HELP_MENU_ABOUT_ITEM = "MENU_HELP_MENU_ABOUT_ITEM";

	public final static String CONNECT_DIALOG_TITLE = "CONNECT_DIALOG_TITLE";

	public static final String CONNECT_DIALOG_BASE_URL_LABEL = "CONNECT_DIALOG_BASE_URL_LABEL";

	public static final String CONNECT_DIALOG_USERNAME_LABEL = "CONNECT_DIALOG_USERNAME_LABEL";

	public static final String CONNECT_DIALOG_PASSWORD_LABEL = "CONNECT_DIALOG_PASSWORD_LABEL";

	public static final String CONNECT_DIALOG_USE_PRIMARY_GROUP_AS_ROUTE = "CONNECT_DIALOG_USE_PRIMARY_GROUP_AS_ROUTE";

	public static final String CONNECT_DIALOG_OK_BUTTON_LABEL = "CONNECT_DIALOG_OK_BUTTON_LABEL";

	public static final String CONNECT_DIALOG_CANCEL_BUTTON_LABEL = "CONNECT_DIALOG_CANCEL_BUTTON_LABEL";

	public static final String TAB_TITLE_GROUP_DETAILS = "TAB_TITLE_GROUP_DETAILS";

	public static final String TAB_TITLE_PERSON_LIST = "TAB_TITLE_PERSON_LIST";

	public static final String GROUP_DETAILS_ID = "GROUP_DETAILS_ID";

	public static final String GROUP_DETAILS_NAME = "GROUP_DETAILS_NAME";

	public static final String GROUP_DETAILS_GROUP_TYPE = "GROUP_DETAILS_GROUP_TYPE";

	public static final String GROUP_DETAILS_IS_LAYER = "GROUP_DETAILS_IS_LAYER";

	public static final String GROUP_DETAILS_TYPE = "GROUP_DETAILS_TYPE";

	public static final String GROUP_DETAILS_EXPORT_ACTION = "GROUP_DETAILS_EXPORT_ACTION";
	
	public static final String GROUP_DETAILS_EXPORT_DIALOG_ACTION = "GROUP_DETAILS_EXPORT_DIALOG_ACTION";

	public static final String ROLE_COUNT_STATISTICS_COLUMN_ID = "ROLE_COUNT_STATISTICS_COLUMN_ID";

	public static final String ROLE_COUNT_STATISTICS_COLUMN_NAME = "ROLE_COUNT_STATISTICS_COLUMN_NAME";

	public static final String ROLE_COUNT_STATISTICS_COLUMN_COUNT = "ROLE_COUNT_STATISTICS_COLUMN_COUNT";

	public static final String PERSON_LIST_COLUMN_ID = "PERSON_LIST_COLUMN_ID";

	public static final String PERSON_LIST_COLUMN_TYPE = "PERSON_LIST_COLUMN_TYPE";

	public static final String PERSON_LIST_COLUMN_FIRSTNAME = "PERSON_LIST_COLUMN_FIRSTNAME";

	public static final String PERSON_LIST_COLUMN_LASTNAME = "PERSON_LIST_COLUMN_LASTNAME";

	public static final String PERSON_LIST_COLUMN_NICKNAME = "PERSON_LIST_COLUMN_NICKNAME";

	public static final String PERSON_LIST_COLUMN_COMPANYNAME = "PERSON_LIST_COLUMN_COMPANYNAME";

	public static final String PERSON_LIST_COLUMN_IS_COMPANY = "PERSON_LIST_COLUMN_IS_COMPANY";

	public static final String PERSON_LIST_COLUMN_GENDER = "PERSON_LIST_COLUMN_GENDER";

	public static final String PERSON_LIST_COLUMN_EMAIL = "PERSON_LIST_COLUMN_EMAIL";

	public static final String PERSON_LIST_COLUMN_ADDRESS = "PERSON_LIST_COLUMN_ADDRESS";

	public static final String PERSON_LIST_COLUMN_ZIPCODE = "PERSON_LIST_COLUMN_ZIPCODE";

	public static final String PERSON_LIST_COLUMN_TOWN = "PERSON_LIST_COLUMN_TOWN";

	public static final String PERSON_LIST_COLUMN_COUNTRY = "PERSON_LIST_COLUMN_COUNTRY";

	public static final String PERSON_LIST_COLUMN_LOCALDEPARTMENTS = "PERSON_LIST_COLUMN_LOCALDEPARTMENTS";

	public static final String ERROR_MSG_LOGIN_FAILED = "ERROR_MSG_LOGIN_FAILED";

	public static final String HIERARCHICAL_CSV_EXPORT_PROGRESS_STRING = "HIERARCHICAL_CSV_EXPORT_PROGRESS_STRING";
	
	public static final String EXPORT_HEADER_FORMAT_GROUP_INFO_AS_HEADER = "EXPORT_HEADER_FORMAT_GROUP_INFO_AS_HEADER";
	
	public static final String EXPORT_HEADER = "EXPORT_HEADER";
	
	public static final String EXPORT_HIERARCHICAL = "EXPORT_HIERARCHICAL";
	
	public static final String EXPORT_HEADER_GROUP_NAME = "EXPORT_HEADER_GROUP_NAME";
	
	public static final String EXPORT_HEADER_ID = "EXPORT_HEADER_ID";
	
	public static final String EXPORT_HEADER_TYPE = "EXPORT_HEADER_TYPE";
	
	public static final String EXPORT_HEADER_HREF = "EXPORT_HEADER_HREF";
	
	public static final String EXPORT_HEADER_ROLE_TYPE = "EXPORT_HEADER_ROLE_TYPE";
	
	public static final String EXPORT_HEADER_SALUTATION = "EXPORT_HEADER_SALUTATION";
	
	public static final String EXPORT_HEADER_TITLE = "EXPORT_HEADER_TITLE";
	
	public static final String EXPORT_HEADER_FIRST_NAME = "EXPORT_HEADER_FIRST_NAME";
	
	public static final String EXPORT_HEADER_LAST_NAME = "EXPORT_HEADER_LAST_NAME";
	
	public static final String EXPORT_HEADER_NICKNAME = "EXPORT_HEADER_NICKNAME";
	
	public static final String EXPORT_HEADER_COMPANY_NAME = "EXPORT_HEADER_COMPANY_NAME";
	
	public static final String EXPORT_HEADER_IS_COMPANY_NAME = "EXPORT_HEADER_IS_COMPANY_NAME";
	
	public static final String EXPORT_HEADER_GENDER = "EXPORT_HEADER_GENDER";
	
	public static final String EXPORT_HEADER_ADDRESS = "EXPORT_HEADER_ADDRESS";
	
	public static final String EXPORT_HEADER_ZIP_CODE = "EXPORT_HEADER_ZIP_CODE";
	
	public static final String EXPORT_HEADER_TOWN = "EXPORT_HEADER_TOWN";
		
	public static final String EXPORT_HEADER_CANTON = "EXPORT_HEADER_CANTON";
	
	public static final String EXPORT_HEADER_COUNTRY = "EXPORT_HEADER_COUNTRY";

	public static final String EXPORT_HEADER_EMAIL = "EXPORT_HEADER_EMAIL";
	
	public static final String EXPORT_HEADER_PHONE = "EXPORT_HEADER_PHONE";
	
	public static final String EXPORT_HEADER_MOBILE_NUMBER = "EXPORT_HEADER_MOBILE_NUMBER";
	
	public static final String EXPORT_HEADER_SALUTATION_PARENTS = "EXPORT_HEADER_SALUTATION_PARENTS";
	
	public static final String EXPORT_HEADER_NAME_PARENTS = "EXPORT_HEADER_NAME_PARENTS";
	
	public static final String EXPORT_HEADER_JS_NUMBER = "EXPORT_HEADER_JS_NUMBER";
	
	public static final String EXPORT_HEADER_NATIONALITY_JS = "EXPORT_HEADER_NATIONALITY_JS";
	
	public static final String EXPORT_HEADER_AHV_NUMBER = "EXPORT_HEADER_AHV_NUMBER";
	
	public static final String EXPORT_HEADER_AHV_NUMBER_OLD = "EXPORT_HEADER_AHV_NUMBER_OLD";
	
	public static final String EXPORT_HEADER_PROFESSION = "EXPORT_HEADER_PROFESSION";
	
	public static final String EXPORT_HEADER_JOINED_DATE = "EXPORT_HEADER_JOINED_DATE";
	
	public static final String EXPORT_HEADER_MEMBER_CARD_NUMBER = "EXPORT_HEADER_MEMBER_CARD_NUMBER";
	
	public static final String EXPORT_HEADER_NATIONALITY = "EXPORT_HEADER_NATIONALITY";
	
	public static final String EXPORT_HEADER_CORRESPONDENCE_LANG = "EXPORT_HEADER_CORRESPONDENCE_LANG";
	
	public static final String EXPORT_HEADER_CONFESSION = "EXPORT_HEADER_CONFESSION";
	
	public static final String EXPORT_HEADER_BIRTHDAY = "EXPORT_HEADER_BIRTHDAY";
	
	public static final String EXPORT_HEADER_PRIMARY_GROUP = "EXPORT_HEADER_PRIMARY_GROUP";
	
	public static final String EXPORT_HEADER_ADDITIONAL_INFORMATION = "EXPORT_HEADER_ADDITIONAL_INFORMATION";
	
	public static final String EXPORT_DIALOG_TITLE = "EXPORT_DIALOG_TITLE";
	
	public static final String EXPORT_DIALOG_GENERAL_INFO_TITLE = "EXPORT_DIALOG_GENERAL_INFO_TITLE";
	
	public static final String EXPORT_DIALOG_FORMAT_LABEL = "EXPORT_DIALOG_FORMAT_LABEL";
	
	public static final String EXPORT_DIALOG_PATH_LABEL = "EXPORT_DIALOG_PATH_LABEL";
	
	public static final String EXPORT_DIALOG_BROWSE_BUTTON = "EXPORT_DIALOG_BROWSE_BUTTON";
	
	public static final String EXPORT_DIALOG_OK_BUTTON_LABEL = "EXPORT_DIALOG_OK_BUTTON_LABEL";
	
	public static final String EXPORT_DIALOG_CANCEL_BUTTON_LABEL = "EXPORT_DIALOG_CANCEL_BUTTON_LABEL";
	
	public static final String EXPORT_DIALOG_ATTRIBUTE_TITLE = "EXPORT_DIALOG_ATTRIBUTE_TITLE";

	private static final ResourceBundle messages = ResourceBundle.getBundle("MessagesBundle", Locale.getDefault());
	
	public static String getTranslatedText(String textToTranslate){
		return messages.getString(textToTranslate);
	}
}